version: '2.4'
services:
    plexconnect:
        container_name: plexconnect
        hostname: plexconnect
        restart: unless-stopped
        image: plexconnect:latest
        ports:
            - 80:80
            - 443:443
            - 53:53/udp
        environment:
            PUID: 1001
            PGID: 1001
            TZ: "Europe/Vilnius"
            THIS_HOST: "192.168.13.55"
            PMS_HOST: "192.168.13.100"
            PMS_PORT: "32400"
            DNS_MASTER: "1.1.1.1"
